jobs:
- job: Angular
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: install
      workingDir:

  - task: Npm@1
    displayName: 'Build Angular'
    inputs:
      command: custom
      customCommand: run build --prod
      workingDir:

  - task: Npm@1
    displayName: 'Run Test Angular'
    inputs:
      command: custom
      customCommand: run e2e
      workingDir:

  - task: CmdLine@2
    displayName: 'firebase publish -m "$(Build.BuildNumber)"'
    inputs:
      command: custom
      customCommand: firebase deploy --token "$(FIREBASE_TOKEN)" -m "$(Build.BuildNumber)"
      workingDir:
