variables:
  buildConfiguration: 'Release'
jobs:
- job: Angular
  steps:
<<<<<<< HEAD
=======
  - task: DeleteFiles@1
    displayName: 'Delete JUnit files'
    inputs:
      SourceFolder: /junit
      Contents: 'TEST*.xml'
  
>>>>>>> d8942a5a9edab5ef1c300d2a0ba5432abb5742e7
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: install
<<<<<<< HEAD
      workingDir:

=======
      workingDir: ./
  
>>>>>>> d8942a5a9edab5ef1c300d2a0ba5432abb5742e7
  - task: Npm@1
    displayName: 'Build Angular'
    inputs:
      command: custom
      customCommand: run build -- --prod
<<<<<<< HEAD
      workingDir:

=======
      workingDir: ./
  
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'angular'
      targetPath: '/dist'
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '/dist'
      ArtifactName: angular2
  
  - task: Npm@1
    displayName: 'Test Angular'
    inputs:
      command: custom
      customCommand: run test -- --watch=false --code-coverage
      workingDir: ./
  
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage Angular results'
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '/coverage/cobertura-coverage.xml'
      reportDirectory: /coverage
      failIfCoverageEmpty: true
  
  - task: PublishTestResults@2
    displayName: 'Publish Angular test results'
    condition: succeededOrFailed()
    inputs:
      searchFolder: $(System.DefaultWorkingDirectory)/junit
      testRunTitle: Angular
      testResultsFormat: JUnit
      testResultsFiles: "**/TESTS*.xml"
  
  - task: Npm@1
    displayName: 'Lint Angular'
    inputs:
      command: custom
      customCommand: run lint --  --format=stylish
      workingDir: ./
  
  - task: Npm@1
    displayName: 'E2E Test Angular'
    inputs:
      command: custom
      customCommand: run e2e
      workingDir: ./
  
  - task: PublishTestResults@2
    displayName: 'Publish Angular E2E test results'
    condition: succeededOrFailed()
    inputs:
      searchFolder: $(System.DefaultWorkingDirectory)/
      testRunTitle: Angular_E2E
      testResultsFormat: JUnit
      testResultsFiles: "**/junit-result.xml"
>>>>>>> d8942a5a9edab5ef1c300d2a0ba5432abb5742e7
