variables:
  buildConfiguration: 'Release'
jobs:
- job: Angular
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: install
      workingDir:

  - task: Npm@1
    displayName: 'Build Angular'
    inputs:
      command: custom
      customCommand: run build -- --prod
      workingDir:

